import { HugeiconsIcon } from "@hugeicons/react";
import {
  AffiliateIcon,
  Agreement02Icon,
  AudioWave01Icon,
  AudioWaveformIcon,
  Award01Icon,
  Basketball01Icon,
  BlushBrush01Icon,
  BlushBrush02Icon,
  BubbleChatIcon,
  Calendar03Icon,
  Camera01Icon,
  CameraVideoIcon,
  ChartNetworkIcon,
  ClapperboardIcon,
  ClipboardCheckIcon,
  ClipboardListIcon,
  ClothesIcon,
  ComputerSettingsIcon,
  ComputerVideoIcon,
  ContentWritingIcon,
  CurtainsIcon,
  Diamond02Icon,
  Dress04Icon,
  Dress07Icon,
  FilePenIcon,
  FlowConnectionIcon,
  FootballIcon,
  HairDryerIcon,
  HammerIcon,
  HandHelpingIcon,
  Idea01Icon,
  JokerIcon,
  KeyframesDoubleIcon,
  MaskTheater01Icon,
  MaskTheater02Icon,
  Megaphone01Icon,
  Mic01Icon,
  PackageIcon,
  PaintBoardIcon,
  PencilRulerIcon,
  ProjectorIcon,
  QuoteUpIcon,
  RunningShoesIcon,
  Scissor01Icon,
  SmartPhone01Icon,
  SpotlightIcon,
  Tag01Icon,
  TheaterIcon,
  ThreadIcon,
  UserGroupIcon,
  UserMultiple02Icon,
  Video01Icon,
  VolleyballIcon,
  Wrench01Icon,
  Yoga01Icon,
  Yoga02Icon,
  CodeIcon,
} from "@hugeicons/core-free-icons";

const roleIcons = {
  coordination: ChartNetworkIcon,
  director: ClapperboardIcon,
  assistant: ClipboardCheckIcon,
  producer: Megaphone01Icon,
  schedule: Calendar03Icon,
  partnership: AffiliateIcon,
  award: Award01Icon,
  admin: ClipboardListIcon,
  volunteer: HandHelpingIcon,
  stage: TheaterIcon,
  props: PackageIcon,
  backstage: CurtainsIcon,
  broadcast: CameraVideoIcon,
  sound: AudioWaveformIcon,
  technical: ComputerSettingsIcon,
  connection: FlowConnectionIcon,
  tools: Wrench01Icon,
  lighting: SpotlightIcon,
  screen: ComputerVideoIcon,
  code: CodeIcon,
  script: FilePenIcon,
  "faculty-director": ClapperboardIcon,
  costume: ClothesIcon,
  "prop-master": HammerIcon,
  art: PaintBoardIcon,
  "sound-operator": AudioWave01Icon,
  "light-operator": SpotlightIcon,
  blocking: UserMultiple02Icon,
  actor: MaskTheater01Icon,
  "supporting-actor": MaskTheater02Icon,
  ensemble: UserGroupIcon,
  vocal: Mic01Icon,
  choreo: Yoga01Icon,
  dance: Yoga02Icon,
  "faculty-screen": ProjectorIcon,
  writing: ContentWritingIcon,
  makeup: BlushBrush01Icon,
  idea: Idea01Icon,
  design: PencilRulerIcon,
  copy: QuoteUpIcon,
  content: SmartPhone01Icon,
  photo: Camera01Icon,
  video: Video01Icon,
  brand: Tag01Icon,
  edit: Scissor01Icon,
  social: BubbleChatIcon,
  motion: KeyframesDoubleIcon,
  fashion: Dress04Icon,
  sewing: ThreadIcon,
  shoe: RunningShoesIcon,
  jewelry: Diamond02Icon,
  hair: HairDryerIcon,
  "fashion-makeup": BlushBrush02Icon,
  "partnership-creative": Agreement02Icon,
  "fashion-director": Dress07Icon,
  volleyball: VolleyballIcon,
  football: FootballIcon,
  basketball: Basketball01Icon,
  joke: JokerIcon,
};

export default function RoleIcon({ type }) {
  return (
    <HugeiconsIcon
      className={`role-icon role-icon--${type}`}
      icon={roleIcons[type] || Idea01Icon}
      size="100%"
      strokeWidth={1.55}
      aria-hidden="true"
    />
  );
}
